#!/bin/bash

# mfetch -  a minimalist fetch to get what you want when you need it

me=$(whoami)
os=$(source /etc/os-release; echo $NAME)
kr=$(uname -r | sed 's/-.*//g')
up=$(uptime -p | sed 's/up //g;s/ days,/d/g;s/ hours,/h/g;s/ minutes/m/g;s/ day,/d/g;s/ hour,/h/g;s/ minute/m/g')
de=$(echo "${XDG_CURRENT_DESKTOP}")
sh=$(basename ${SHELL})

echo -e "
\e[34m me: \e[0m${me}
\e[34m os: \e[0m${os}
\e[34m kr: \e[0m${kr}
\e[34m up: \e[0m${up}
\e[34m de: \e[0m${de}
\e[34m sh: \e[0m${sh}"
echo -e \\n \\e[10{0..7}m\ \ \\e[m \\n \\e[4{0..7}m\ \ \\e[m \\n

# ^^^ https://github.com/dylanaraps/bin/blob/master/16
