#!/bin/bash

# mfetch -  a minimalist fetch

me=$(whoami)
os=$(source /etc/os-release; echo $NAME)
kr=$(uname -r | cut -d - -f1)
up=$(uptime -p | sed 's/up //')
sh=$(basename ${SHELL})
mem=$(free -h | awk '/Mem:/ {print $3 "/" $2}')

echo -e "\e[34m me: \e[0m$me"
echo -e "\e[34m os: \e[0m$os"
echo -e "\e[34m kr: \e[0m$kr"
echo -e "\e[34m up: \e[0m$up"
echo -e "\e[34m sh: \e[0m$sh"
echo -e "\e[34m mem: \e[0m$mem"
